---
- name: OpenStack Service Setup
  hosts: all
  become: yes
  vars_files:
    - roles/neutron/tasks/main.yml
    - roles//horizon/tasks/main.yml
    - roles//cinder/tasks/main.yml

  tasks:
    - name: Configure and Install Neutron
      include_role:
        name: neutron

    - name: Configure and Install Horizon
      include_role:
        name: horizon

    - name: Configure and Install Cinder
      include_role:
        name: cinder
